version: '3.8'

services:
  app:
    container_name: parker-app
    image: parker-backend:latest  # GitHub Actions에서 빌드된 이미지 사용
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    networks:
      - parker-network

  db:
    container_name: parker-mysql
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - parker-network

  redis:
    container_name: parker-redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - parker-network

networks:
  parker-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
