name: "Deploy Request"
description: "배포 작업"
title: "[Deploy] "

body:
  - type: input
    id: "deploy_title"
    attributes:
      label: "📝 제목"
      placeholder: "배포 작업의 제목을 간단히 적어 주세요."

  - type: textarea
    id: "deploy_details"
    attributes:
      label: "📋 작업 내용"
      placeholder: |
        배포와 관련된 작업 내용을 자세히 작성해 주세요.
        예)
        - 배포 대상: **프론트엔드 서버, 백엔드 서버**
        - 변경 사항 요약: **회원가입 기능 추가, 로그인 API 성능 개선**
        - 예상 영향 범위: **로그인, 회원가입 관련 모듈**
