name: "Refactor Report"
description: "리팩토링"
title: "[Refactor] "

body:
  - type: input
    id: "refactor_target"
    attributes:
      label: "🛠 대상"
      placeholder: "리팩토링할 대상 영역을 간략히 작성해 주세요."

  - type: textarea
    id: "refactor_description"
    attributes:
      label: "📄 설명"
      placeholder: |
        리팩토링 작업의 목적과 이유를 자세히 작성해 주세요.

  - type: textarea
    id: "expected_effect"
    attributes:
      label: "✅ 기대 효과"
      placeholder: |
        리팩토링 후 기대되는 효과를 작성해 주세요.


  - type: input
    id: "reference_links"
    attributes:
      label: "🔗 참고 자료"
      placeholder: "관련 문서나 링크가 있다면 작성해 주세요. 예) [리팩토링 가이드](https://example.com/refactoring-guide)"
