name: Deploy to AWS EC2

on:
  push:
    branches:
      - deploy/#47/aws-ec2-docker

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd /home/ec2-user/parker
            git pull origin deploy/#47/aws-ec2-docker
            docker-compose down
            docker-compose up -d --build
          EOF
